// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using decorativeplant_be.Infrastructure.Data;

#nullable disable

namespace decorativeplant_be.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423233429_AddPlantDiagnosisResolvedAtUtc")]
    partial class AddPlantDiagnosisResolvedAtUtc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AiChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AttachmentMimeType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AttachmentUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiagnosisJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("RecommendationsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId", "CreatedAt");

                    b.ToTable("ai_chat_message", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AiChatThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ai_chat_thread", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AiTrainingFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedbackContent")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ai_training_feedback", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ArPreviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScanJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TokenSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("ar_preview_session", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AutomationExecutionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("automation_execution_log", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Actions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Conditions")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Schedule")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("automation_rule", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.BatchStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("HealthStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastCountInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Quantities")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("LocationId");

                    b.ToTable("batch_stock", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BranchType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Long")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("jsonb");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("branch", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.CareLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("GardenPlantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Images")
                        .HasColumnType("jsonb");

                    b.Property<string>("LogInfo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GardenPlantId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("care_log", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.CareSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("GardenPlantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TaskInfo")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("GardenPlantId");

                    b.ToTable("care_schedule", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Info")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.CultivationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PerformedBy");

                    b.ToTable("cultivation_log", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.FeatureUsageQuota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("PeriodEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuotaLimit")
                        .HasColumnType("integer");

                    b.Property<string>("QuotaPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("QuotaUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("feature_usage_quota", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.GardenPlant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TaxonomyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaxonomyId");

                    b.HasIndex("UserId");

                    b.ToTable("garden_plant", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.HealthIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("Images")
                        .HasColumnType("jsonb");

                    b.Property<string>("IncidentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StatusInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uuid");

                    b.Property<string>("TreatmentInfo")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("StockId");

                    b.ToTable("health_incident", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.InventoryLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("inventory_location", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.IotAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AlertInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("ComponentKey")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionInfo")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("iot_alert", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.IotDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActivityLog")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Components")
                        .HasColumnType("jsonb");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("LocationId");

                    b.ToTable("iot_device", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.OrderHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("jsonb");

                    b.Property<string>("Financials")
                        .HasColumnType("jsonb");

                    b.Property<string>("Notes")
                        .HasColumnType("jsonb");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PickupInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TypeInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("DeliveredAt")
                        .HasDatabaseName("IX_order_header_DeliveredAt_delivered")
                        .HasFilter("\"Status\" = 'delivered'");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("order_header", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pricing")
                        .HasColumnType("jsonb");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Snapshots")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ListingId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StockId");

                    b.ToTable("order_item", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("payment_transaction", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BatchCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentTotalQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("InitialQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("Specs")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaxonomyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ParentBatchId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("TaxonomyId");

                    b.ToTable("plant_batch", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("PlantCategories");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiResult")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Feedback")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("GardenPlantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserInput")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GardenPlantId");

                    b.HasIndex("UserId");

                    b.ToTable("plant_diagnosis", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantTaxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CareInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommonNames")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GrowthInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TaxonomyInfo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ScientificName")
                        .IsUnique();

                    b.ToTable("plant_taxonomy", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PremiumFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvailableInPlans")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeatureKey")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("premium_feature", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ProductListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Images")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProductInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("SeoInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("StatusInfo")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("BranchId");

                    b.ToTable("product_listing", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ProductModelAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BoundingBox")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DefaultScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,4)")
                        .HasDefaultValue(1m);

                    b.Property<string>("GlbUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("ProductListingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductListingId")
                        .IsUnique();

                    b.ToTable("product_model_asset", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ProductReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Images")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusInfo")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("product_review", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("promotion", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.RecommendationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SeedSignalsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("recommendation_log", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ReturnRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Images")
                        .HasColumnType("jsonb");

                    b.Property<string>("Info")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("return_request", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.SensorReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ComponentKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("sensor_reading", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Shipping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CarrierInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("DeliveryDetails")
                        .HasColumnType("jsonb");

                    b.Property<string>("Events")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("shipping", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ShippingZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryTimeConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("FeeConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("Locations")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("shipping_zone", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ShoppingCart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Items")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("shopping_cart", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.StaffAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Permissions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("StaffId");

                    b.ToTable("staff_assignment", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.StockAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetaInfo")
                        .HasColumnType("jsonb");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid?>("StockId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("stock_adjustment", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.StockTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromBranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogisticsInfo")
                        .HasColumnType("jsonb");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ToBranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransferCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("FromBranchId");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("ToBranchId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("stock_transfer", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("jsonb");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("supplier", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("jsonb");

                    b.HasKey("Key");

                    b.ToTable("system_config", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Addresses")
                        .HasColumnType("jsonb");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("BudgetRange")
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HardinessZone")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool?>("HasChildrenOrPets")
                        .HasColumnType("boolean");

                    b.Property<string>("HumidityLevel")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlacementLocation")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("PlantGoals")
                        .HasColumnType("jsonb");

                    b.Property<string>("PreferredStyle")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoomTemperatureRange")
                        .HasColumnType("text");

                    b.Property<string>("SpaceSize")
                        .HasColumnType("text");

                    b.Property<string>("SunlightExposure")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WateringFrequency")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AmountPaid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("BillingCycle")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("user_subscription", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Info")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Rules")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("voucher", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ListingId")
                        .IsUnique();

                    b.ToTable("wishlist_item", (string)null);
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AiChatMessage", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.AiChatThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AiChatThread", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AiTrainingFeedback", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("AiTrainingFeedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AutomationExecutionLog", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.AutomationRule", "Rule")
                        .WithMany("ExecutionLogs")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AutomationRule", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.IotDevice", "Device")
                        .WithMany("AutomationRules")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.BatchStock", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantBatch", "Batch")
                        .WithMany("BatchStocks")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.InventoryLocation", "Location")
                        .WithMany("BatchStocks")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Branch", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.CareLog", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.GardenPlant", "GardenPlant")
                        .WithMany("CareLogs")
                        .HasForeignKey("GardenPlantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("decorativeplant_be.Domain.Entities.CareSchedule", "Schedule")
                        .WithMany("CareLogs")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GardenPlant");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.CareSchedule", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.GardenPlant", "GardenPlant")
                        .WithMany("CareSchedules")
                        .HasForeignKey("GardenPlantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GardenPlant");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.CultivationLog", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantBatch", "Batch")
                        .WithMany("CultivationLogs")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.InventoryLocation", "Location")
                        .WithMany("CultivationLogs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "PerformedByUser")
                        .WithMany("CultivationLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("Location");

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.FeatureUsageQuota", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.GardenPlant", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantTaxonomy", "Taxonomy")
                        .WithMany("GardenPlants")
                        .HasForeignKey("TaxonomyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("GardenPlants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Taxonomy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.HealthIncident", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantBatch", "Batch")
                        .WithMany("HealthIncidents")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.BatchStock", "Stock")
                        .WithMany("HealthIncidents")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.InventoryLocation", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("InventoryLocations")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.InventoryLocation", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.IotAlert", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.IotDevice", "Device")
                        .WithMany("IotAlerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.IotDevice", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("IotDevices")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.InventoryLocation", "Location")
                        .WithMany("IotDevices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Notification", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.OrderHeader", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId");

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedStaff");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantBatch", "Batch")
                        .WithMany("OrderItems")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("OrderItems")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.ProductListing", "Listing")
                        .WithMany("OrderItems")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.OrderHeader", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("decorativeplant_be.Domain.Entities.BatchStock", "Stock")
                        .WithMany("OrderItems")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("Branch");

                    b.Navigation("Listing");

                    b.Navigation("Order");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.OrderHeader", "Order")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantBatch", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("PlantBatches")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.PlantBatch", "ParentBatch")
                        .WithMany("ChildBatches")
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PlantBatches")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.PlantTaxonomy", "Taxonomy")
                        .WithMany("PlantBatches")
                        .HasForeignKey("TaxonomyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("ParentBatch");

                    b.Navigation("Supplier");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantCategory", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantDiagnosis", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.GardenPlant", "GardenPlant")
                        .WithMany("PlantDiagnoses")
                        .HasForeignKey("GardenPlantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("GardenPlant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantTaxonomy", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantCategory", "Category")
                        .WithMany("PlantTaxonomies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ProductListing", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantBatch", "Batch")
                        .WithMany("ProductListings")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("ProductListings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ProductModelAsset", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.ProductListing", "ProductListing")
                        .WithMany()
                        .HasForeignKey("ProductListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductListing");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ProductReview", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.ProductListing", "Listing")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("decorativeplant_be.Domain.Entities.OrderHeader", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Listing");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Promotion", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("Promotions")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ReturnRequest", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.OrderHeader", "Order")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("ReturnRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.IotDevice", "Device")
                        .WithMany("SensorReadings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Shipping", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.OrderHeader", "Order")
                        .WithMany("Shippings")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ShippingZone", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("ShippingZones")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ShoppingCart", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.StaffAssignment", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "Staff")
                        .WithMany("StaffAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.StockAdjustment", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.BatchStock", "Stock")
                        .WithMany("StockAdjustments")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.StockTransfer", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.PlantBatch", "Batch")
                        .WithMany("StockTransfers")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "FromBranch")
                        .WithMany("StockTransfersFrom")
                        .HasForeignKey("FromBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.InventoryLocation", "FromLocation")
                        .WithMany("TransfersFrom")
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "ToBranch")
                        .WithMany("StockTransfersTo")
                        .HasForeignKey("ToBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("decorativeplant_be.Domain.Entities.InventoryLocation", "ToLocation")
                        .WithMany("TransfersTo")
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");

                    b.Navigation("FromBranch");

                    b.Navigation("FromLocation");

                    b.Navigation("ToBranch");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.Branch", "Branch")
                        .WithMany("Vouchers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.WishlistItem", b =>
                {
                    b.HasOne("decorativeplant_be.Domain.Entities.ProductListing", "Listing")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("decorativeplant_be.Domain.Entities.UserAccount", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AiChatThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.AutomationRule", b =>
                {
                    b.Navigation("ExecutionLogs");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.BatchStock", b =>
                {
                    b.Navigation("HealthIncidents");

                    b.Navigation("OrderItems");

                    b.Navigation("StockAdjustments");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Branch", b =>
                {
                    b.Navigation("InventoryLocations");

                    b.Navigation("IotDevices");

                    b.Navigation("OrderItems");

                    b.Navigation("PlantBatches");

                    b.Navigation("ProductListings");

                    b.Navigation("Promotions");

                    b.Navigation("ShippingZones");

                    b.Navigation("StaffAssignments");

                    b.Navigation("StockTransfersFrom");

                    b.Navigation("StockTransfersTo");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.CareSchedule", b =>
                {
                    b.Navigation("CareLogs");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Company", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.GardenPlant", b =>
                {
                    b.Navigation("CareLogs");

                    b.Navigation("CareSchedules");

                    b.Navigation("PlantDiagnoses");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.InventoryLocation", b =>
                {
                    b.Navigation("BatchStocks");

                    b.Navigation("ChildLocations");

                    b.Navigation("CultivationLogs");

                    b.Navigation("IotDevices");

                    b.Navigation("TransfersFrom");

                    b.Navigation("TransfersTo");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.IotDevice", b =>
                {
                    b.Navigation("AutomationRules");

                    b.Navigation("IotAlerts");

                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.OrderHeader", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PaymentTransactions");

                    b.Navigation("ReturnRequests");

                    b.Navigation("Shippings");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantBatch", b =>
                {
                    b.Navigation("BatchStocks");

                    b.Navigation("ChildBatches");

                    b.Navigation("CultivationLogs");

                    b.Navigation("HealthIncidents");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductListings");

                    b.Navigation("StockTransfers");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("PlantTaxonomies");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.PlantTaxonomy", b =>
                {
                    b.Navigation("GardenPlants");

                    b.Navigation("PlantBatches");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.ProductListing", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductReviews");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PlantBatches");
                });

            modelBuilder.Entity("decorativeplant_be.Domain.Entities.UserAccount", b =>
                {
                    b.Navigation("AiTrainingFeedbacks");

                    b.Navigation("CultivationLogs");

                    b.Navigation("GardenPlants");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("ProductReviews");

                    b.Navigation("ReturnRequests");

                    b.Navigation("ShoppingCarts");

                    b.Navigation("StaffAssignments");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
