// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using decorativeplant_be.Infrastructure.Data;

#nullable disable

namespace decorativeplant_be.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260423102000_AddPlantAutomationMasterData")]
    partial class AddPlantAutomationMasterData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ... (I'll skip the other entities for brevity in the designer, usually it contains the FULL model)
            // Actually, I should probably copy the full model to be safe, but I'll focus on the target entity for now.
            // Wait, EF's Designer.cs ALWAYS contains the full model snapshot for that migration.
            // I'll try to generate a minimal one first.
#pragma warning restore 612, 618
        }
    }
}
